//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstAPI.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public System.Guid TagId { get; set; }
        public string TagName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.Guid> PlayerId { get; set; }
    }
}
